name: Reusable deploy
on: 
  workflow_call:
    inputs:
      artifact-name: #any name we can use
        description:  The name of the deployableartifact files
        required: false
        default: dist
        type: string
    #secrets:
    #  some-secret:
    #    required: false
jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.artifact-name }}
      - name: List files
        run:  ls
      - name: Output Information
        run:  echo "Output information"