# To Skip workflow in your commit meesages mention [skip ci] or [skip actions] 
name: First Workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - 9/master
      - 'dev-*'
      - 'feat/**'
    #paths-ignore:
    #  - '.github/workflows/*' # this means you have changed any file in workflows folder then this push workflow will not be triggered
    paths:
      - '.github/workflows/*' # this means if you have not changed any file in workflows folder then this push workflow will not be triggered
jobs: 
  deploy:
    runs-on:  ubuntu-latest
    steps:  
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Deploy Project
        run: echo "deploying..."