name: Action Workflow
on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  pull_request:
    types: [closed, opened, assigned, reopened]
jobs:
  run-gitgub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 # https://github.com/actions/hello-world-javascript-action
        #uses: actions/hello-world-javascript-action@main // we can metion branch here 
        #uses: actions/hello-world-javascript-action@be24b1ba147bc3acbf8f3f3665b3cca7e4f60a76 // we can also mention commit ID here
        with:
          who-to-greet: Ateyendra # it takes input with the key name: who-to-greet
      - name: Log Greeting Time
        run:  echo "${{ steps.greet.outputs.time }}" # it also produces some output with key name: time

